[server]
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#1A1A2E"
backgroundColor = "#EEF1F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A2E"
font = "sans serif"
